// <auto-generated />
namespace LCCS_School_Parent_Communication_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedgroupList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedgroupList));
        
        string IMigrationMetadata.Id
        {
            get { return "202201140527394_addedgroupList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
